# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['webview.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt6.QtOpenGL',
        'PyQt6.QtMultimedia',
        'PyQt6.QtPositioning',
        'PyQt6.QtQuick3D',
        'PyQt6.QtRemoteObjects',
        'PyQt6.QtSensors',
        'PyQt6.QtTest',
        'PyQt6.QtTextToSpeech',
        # 'PyQt6.QtWebChannel',
        'PyQt6.QtWebSockets',
        'PyQt6.QtSvg',
        'PyQt6.QtShaderTools',
        'PyQt6.QtPdf',
        'PyQt6.QtPdfQuick',
        'PyQt6.QtQuickControls2',
        'PyQt6.QtQuickDialogs2',
        'PyQt6.QtQuickLayouts',
        'PyQt6.QtQuickParticles',
        'PyQt6.QtQuickShapes',
        'PyQt6.QtQuickTimeline',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# Exclude specific binaries by name
binaries_to_exclude = [
    'opengl32sw.dll',
    'Qt6Multimedia.dll',
    'Qt6MultimediaQuick.dll',
    'Qt6Positioning.dll',
    'Qt6PositioningQuick.dll',
    'Qt6Quick3D.dll',
    'Qt6Quick3DAssetImport.dll',
    'Qt6Quick3DAssetUtils.dll',
    'Qt6Quick3DEffects.dll',
    'Qt6Quick3DHelpers.dll',
    'Qt6Quick3DHelpersImpl.dll',
    'Qt6Quick3DParticles.dll',
    'Qt6Quick3DPhysics.dll',
    'Qt6Quick3DPhysicsHelpers.dll',
    'Qt6Quick3DRuntimeRender.dll',
    'Qt6Quick3DSpatialAudio.dll',
    'Qt6Quick3DUtils.dll',
    'Qt6QuickControls2.dll',
    'Qt6QuickControls2Basic.dll',
    'Qt6QuickControls2BasicStyleImpl.dll',
    'Qt6QuickControls2Fusion.dll',
    'Qt6QuickControls2FusionStyleImpl.dll',
    'Qt6QuickControls2Imagine.dll',
    'Qt6QuickControls2ImagineStyleImpl.dll',
    'Qt6QuickControls2Impl.dll',
    'Qt6QuickControls2Material.dll',
    'Qt6QuickControls2MaterialStyleImpl.dll',
    'Qt6QuickControls2Universal.dll',
    'Qt6QuickControls2UniversalStyleImpl.dll',
    'Qt6QuickDialogs2.dll',
    'Qt6QuickDialogs2QuickImpl.dll',
    'Qt6QuickDialogs2Utils.dll',
    'Qt6QuickLayouts.dll',
    'Qt6QuickParticles.dll',
    'Qt6QuickShapes.dll',
    'Qt6QuickTest.dll',
    'Qt6QuickTimeline.dll',
    'Qt6QuickTimelineBlendTrees.dll',
    'Qt6RemoteObjects.dll',
    'Qt6RemoteObjectsQml.dll',
    'Qt6Sensors.dll',
    'Qt6SensorsQuick.dll',
    'Qt6ShaderTools.dll',
    'Qt6SpatialAudio.dll',
    'Qt6Svg.dll',
    'Qt6Test.dll',
    'Qt6TextToSpeech.dll',
    'Qt6WebChannel.dll',
    'Qt6WebChannelQuick.dll',
    'Qt6WebSockets.dll',
]

a.binaries = [b for b in a.binaries if b[0].split('/')[-1] not in binaries_to_exclude]


exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='webview',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='webview',
)
