name: Build for Windows x64

on:
  release:
    types: [published, edited]

  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-legacy.txt

      - name: Build for Win64
        id: build-win64
        run: |
          pyinstaller ArcherLinkWebView.spec
          ls dist  # Print contents of the dist directory

      - name: Export dist directory
        if: success()  # Only proceed if the build succeeded
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact
          path: ./dist

  upload-release-asset:
    name: Upload Release Asset
    runs-on: ubuntu-latest

    needs: build
    if: github.event_name == 'release'
          
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact

      - name: List dir
        run: |
          ls

      - name: Find file to upload
        id: find-file
        run: |
          file=$(find ./ -type f -name "ArcherLinkWebView*.exe")
          echo "file_path=$file" >> $GITHUB_ENV
          filename=$(basename "$file")
          echo "file_name=$filename" >> $GITHUB_ENV

      - name: Upload a file to Release Assets
        id: upload-release-asset
#        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.file_path }}
          asset_name: ${{ env.file_name }}
          asset_content_type: application/octet-stream